### ISSUE TITLE
Possible to use node-pre-gyp instead of nodegyp in eventloop stats

### ISSUE THREAD

**Issue by devarajchidambaram** [bripkens/event-loop-stats#3]
Hi,

https://www.npmjs.com/package/@risingstack/event-loop-stats

Risingstack using node-pre-gyp compile c++ code,  similarly is this possible to implement like them in event loop stats NPM.?

**Comment by bripkens** [comment]
Unfortunately I do not have the capacity to do this, especially considering that I would need to host these pre-built artifacts. Do you have a solution for this?

**Comment by devarajchidambaram** [comment]
I dont have solution
