### ISSUE TITLE
What is the meaning of Eventloop max, min time?

### ISSUE THREAD

**Issue by devarajchidambaram** [bripkens/event-loop-stats#4]
Hi,

max: Maximum number of milliseconds spent in a **SINGLE LOOP** since last sense call.
min: Minimum number of milliseconds spent in a **SINGLE LOOP** since last sense call.

I don't understand what is the meaning max number of ms spend in a **SINGLE LOOP**?

When & what are the scenarios the event loop time will increase?

If you anyone have a link please send it to me.

**Comment by bripkens** [comment]
You can read up on the Node.js event loop over here: https://nodejs.org/en/docs/guides/event-loop-timers-and-nexttick/
